In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from keras.models import load_model
model=load_model('CNNnew.hdf5')

In [6]:
df=pd.read_csv('test.csv')

In [7]:
df.head()#784 pixels in 1-dimension . Convert it to 28x28

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel780  pixel781  pixel782  pixel783  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 784 columns]

In [8]:
df=pd.read_csv('test.csv').values

In [ ]:
df.shape #28000 Images of size 74 i.e. 28x28

(5741, 784)

In [ ]:
df[0]  #First Image

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,  10.,  17.,  17.,  17.,  17.,  81., 180., 180.,  35.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0., 13

In [ ]:
temp= np.reshape(df[0],(28,28)) #It will reduce it to 28x28

In [ ]:
print(df[0].shape)
print(temp.shape) #From 784 columns to 28 columns

(784,)
(28, 28)


# Similarly , We are going to reshape all the images from 784 columns to 28x28 .

In [ ]:
temp #It has 28 rows with each entry ranging from 0 to 253

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  10.,
         17.,  17.,  17.,  17.,  81., 180., 180.,  35.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0

In [ ]:
temp=temp/255
print(temp)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.    

In [ ]:
temp=np.reshape(temp , (1,28,28,1))

In [ ]:
model.predict(temp)

#These values returns us the probablity distribution w.r.t to indices.

1/1 [==============================] - 2s 2s/step


array([[6.8019413e-18, 7.0774917e-17, 1.0000000e+00, 3.7383257e-15,
        7.7847998e-16, 1.0842848e-16, 2.9078504e-21, 1.9890689e-10,
        5.1076367e-16, 1.6709437e-17]], dtype=float32)

In [ ]:
np.argmax(model.predict(temp))
#We are getting the value as 2 as it has the highest probablity . It means the image is most probably a 1.

1/1 [==============================] - 0s 18ms/step


2

In [2]:
r=[]# It will contain predictions of 28000 images.

for i in range(len(df)):#Traverse through rows
  img = np.reshape(df[i],(28,28))
  img=img/255.0 #Values will be scaled down b/w 0 to 1.
  img = np.reshape(img , (1,28,28,1))#Expanding it to 4-dimension to pass it to neural network.
  r.append(str(np.argmax(model.predict(img))))

NameError: name 'df' is not defined

NameError: name 'r' is not defined